import type { GalleryImageAsset } from "./GalleryImage";

// Generated by local-utils convert-media. Do not edit by hand.
export const generatedMediaAssets = {
    "misc/home-bg-sapphi": {
        src: "/media/misc/home-bg-sapphi.webp",
        width: 1600,
        height: 817,
    },
    "misc/pudle-cover": {
        src: "/media/misc/pudle-cover.webp",
        width: 1280,
        height: 300,
    },
} satisfies Record<string, GalleryImageAsset>;
