import type { WorkEntryImageVariants } from "../works/WorkEntryImage";

// Generated by local-utils convert-media. Do not edit by hand.
export const generatedGalleryImages = {
    "gallery/adulty-derg": {
        full: {
            src: "/media/gallery/adulty-derg.full.jpg",
            width: 2364,
            height: 3416,
        },
        preview: {
            src: "/media/gallery/adulty-derg.preview.webp",
            width: 1107,
            height: 1600,
        },
        thumb: {
            src: "/media/gallery/adulty-derg.thumb.webp",
            width: 332,
            height: 480,
        },
    },
    "gallery/anshu-sit": {
        full: {
            src: "/media/gallery/anshu-sit.full.png",
            width: 1348,
            height: 1280,
        },
        preview: {
            src: "/media/gallery/anshu-sit.preview.webp",
            width: 1348,
            height: 1280,
        },
        thumb: {
            src: "/media/gallery/anshu-sit.thumb.webp",
            width: 480,
            height: 455,
        },
    },
    "gallery/aquafrust": {
        full: {
            src: "/media/gallery/aquafrust.full.png",
            width: 3190,
            height: 3181,
        },
        preview: {
            src: "/media/gallery/aquafrust.preview.webp",
            width: 1600,
            height: 1595,
        },
        thumb: {
            src: "/media/gallery/aquafrust.thumb.webp",
            width: 480,
            height: 478,
        },
    },
    "gallery/art-fight-2026/attacks/aheniru": {
        full: {
            src: "/media/gallery/art-fight-2026/attacks/aheniru.full.png",
            width: 6960,
            height: 2475,
        },
        preview: {
            src: "/media/gallery/art-fight-2026/attacks/aheniru.preview.webp",
            width: 1600,
            height: 568,
        },
        thumb: {
            src: "/media/gallery/art-fight-2026/attacks/aheniru.thumb.webp",
            width: 480,
            height: 170,
        },
    },
    "gallery/art-fight-2026/attacks/amonnonza": {
        full: {
            src: "/media/gallery/art-fight-2026/attacks/amonnonza.full.png",
            width: 6720,
            height: 5668,
        },
        preview: {
            src: "/media/gallery/art-fight-2026/attacks/amonnonza.preview.webp",
            width: 1600,
            height: 1349,
        },
        thumb: {
            src: "/media/gallery/art-fight-2026/attacks/amonnonza.thumb.webp",
            width: 480,
            height: 404,
        },
    },
    "gallery/art-fight-2026/attacks/captainraven": {
        full: {
            src: "/media/gallery/art-fight-2026/attacks/captainraven.full.png",
            width: 4320,
            height: 2160,
        },
        preview: {
            src: "/media/gallery/art-fight-2026/attacks/captainraven.preview.webp",
            width: 1600,
            height: 800,
        },
        thumb: {
            src: "/media/gallery/art-fight-2026/attacks/captainraven.thumb.webp",
            width: 480,
            height: 240,
        },
    },
    "gallery/art-fight-2026/attacks/jinsym": {
        full: {
            src: "/media/gallery/art-fight-2026/attacks/jinsym.full.png",
            width: 4320,
            height: 9924,
        },
        preview: {
            src: "/media/gallery/art-fight-2026/attacks/jinsym.preview.webp",
            width: 696,
            height: 1600,
        },
        thumb: {
            src: "/media/gallery/art-fight-2026/attacks/jinsym.thumb.webp",
            width: 208,
            height: 480,
        },
    },
    "gallery/art-fight-2026/attacks/rhaeloth": {
        full: {
            src: "/media/gallery/art-fight-2026/attacks/rhaeloth.full.mp4",
            width: 1920,
            height: 1080,
        },
        preview: {
            src: "/media/gallery/art-fight-2026/attacks/rhaeloth.preview.mp4",
            width: 1920,
            height: 1080,
        },
        thumb: {
            src: "/media/gallery/art-fight-2026/attacks/rhaeloth.thumb.mp4",
            width: 1920,
            height: 1080,
        },
    },
    "gallery/art-fight-2026/attacks/snowsquall": {
        full: {
            src: "/media/gallery/art-fight-2026/attacks/snowsquall.full.png",
            width: 7680,
            height: 4320,
        },
        preview: {
            src: "/media/gallery/art-fight-2026/attacks/snowsquall.preview.webp",
            width: 1600,
            height: 900,
        },
        thumb: {
            src: "/media/gallery/art-fight-2026/attacks/snowsquall.thumb.webp",
            width: 480,
            height: 270,
        },
    },
    "gallery/art-fight-2026/attacks/tiffymew": {
        full: {
            src: "/media/gallery/art-fight-2026/attacks/tiffymew.full.mp4",
            width: 2254,
            height: 1080,
        },
        preview: {
            src: "/media/gallery/art-fight-2026/attacks/tiffymew.preview.mp4",
            width: 2254,
            height: 1080,
        },
        thumb: {
            src: "/media/gallery/art-fight-2026/attacks/tiffymew.thumb.mp4",
            width: 2254,
            height: 1080,
        },
    },
    "gallery/art-fight-2026/attacks/vviiscerall": {
        full: {
            src: "/media/gallery/art-fight-2026/attacks/vviiscerall.full.png",
            width: 9036,
            height: 4000,
        },
        preview: {
            src: "/media/gallery/art-fight-2026/attacks/vviiscerall.preview.webp",
            width: 1600,
            height: 708,
        },
        thumb: {
            src: "/media/gallery/art-fight-2026/attacks/vviiscerall.thumb.webp",
            width: 480,
            height: 212,
        },
    },
    "gallery/art-fight-2026/attacks/warp": {
        full: {
            src: "/media/gallery/art-fight-2026/attacks/warp.full.png",
            width: 7658,
            height: 4340,
        },
        preview: {
            src: "/media/gallery/art-fight-2026/attacks/warp.preview.webp",
            width: 1600,
            height: 906,
        },
        thumb: {
            src: "/media/gallery/art-fight-2026/attacks/warp.thumb.webp",
            width: 480,
            height: 272,
        },
    },
    "gallery/art-fight-2026/attacks/wwco": {
        full: {
            src: "/media/gallery/art-fight-2026/attacks/wwco.full.png",
            width: 11392,
            height: 3858,
        },
        preview: {
            src: "/media/gallery/art-fight-2026/attacks/wwco.preview.webp",
            width: 1600,
            height: 541,
        },
        thumb: {
            src: "/media/gallery/art-fight-2026/attacks/wwco.thumb.webp",
            width: 480,
            height: 162,
        },
    },
    "gallery/art-fight-2026/characters/iywralyx-2026-thumb": {
        full: {
            src: "/media/gallery/art-fight-2026/characters/iywralyx-2026-thumb.full.png",
            width: 1440,
            height: 1440,
        },
        preview: {
            src: "/media/gallery/art-fight-2026/characters/iywralyx-2026-thumb.preview.webp",
            width: 1440,
            height: 1440,
        },
        thumb: {
            src: "/media/gallery/art-fight-2026/characters/iywralyx-2026-thumb.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/art-fight-2026/characters/vaiezzell-2026-thumb": {
        full: {
            src: "/media/gallery/art-fight-2026/characters/vaiezzell-2026-thumb.full.png",
            width: 1440,
            height: 1440,
        },
        preview: {
            src: "/media/gallery/art-fight-2026/characters/vaiezzell-2026-thumb.preview.webp",
            width: 1440,
            height: 1440,
        },
        thumb: {
            src: "/media/gallery/art-fight-2026/characters/vaiezzell-2026-thumb.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/astra-refs/curi": {
        full: {
            src: "/media/gallery/astra-refs/curi.full.png",
            width: 6162,
            height: 4549,
        },
        preview: {
            src: "/media/gallery/astra-refs/curi.preview.webp",
            width: 1600,
            height: 1181,
        },
        thumb: {
            src: "/media/gallery/astra-refs/curi.thumb.webp",
            width: 480,
            height: 354,
        },
    },
    "gallery/astra-refs/pyrinth": {
        full: {
            src: "/media/gallery/astra-refs/pyrinth.full.png",
            width: 6248,
            height: 4232,
        },
        preview: {
            src: "/media/gallery/astra-refs/pyrinth.preview.webp",
            width: 1600,
            height: 1083,
        },
        thumb: {
            src: "/media/gallery/astra-refs/pyrinth.thumb.webp",
            width: 480,
            height: 325,
        },
    },
    "gallery/astra-refs/staaria": {
        full: {
            src: "/media/gallery/astra-refs/staaria.full.png",
            width: 2656,
            height: 2238,
        },
        preview: {
            src: "/media/gallery/astra-refs/staaria.preview.webp",
            width: 1600,
            height: 1348,
        },
        thumb: {
            src: "/media/gallery/astra-refs/staaria.thumb.webp",
            width: 480,
            height: 404,
        },
    },
    "gallery/bigasha": {
        full: {
            src: "/media/gallery/bigasha.full.png",
            width: 2656,
            height: 1466,
        },
        preview: {
            src: "/media/gallery/bigasha.preview.webp",
            width: 1600,
            height: 883,
        },
        thumb: {
            src: "/media/gallery/bigasha.thumb.webp",
            width: 480,
            height: 264,
        },
    },
    "gallery/bookwyrm-dgc-crossover-1": {
        full: {
            src: "/media/gallery/bookwyrm-dgc-crossover-1.full.png",
            width: 2000,
            height: 2000,
        },
        preview: {
            src: "/media/gallery/bookwyrm-dgc-crossover-1.preview.webp",
            width: 1600,
            height: 1600,
        },
        thumb: {
            src: "/media/gallery/bookwyrm-dgc-crossover-1.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/bulb/bulb": {
        full: {
            src: "/media/gallery/bulb/bulb.full.png",
            width: 4458,
            height: 3119,
        },
        preview: {
            src: "/media/gallery/bulb/bulb.preview.webp",
            width: 1600,
            height: 1119,
        },
        thumb: {
            src: "/media/gallery/bulb/bulb.thumb.webp",
            width: 480,
            height: 335,
        },
    },
    "gallery/bulb/img-3133": {
        full: {
            src: "/media/gallery/bulb/img-3133.full.jpg",
            width: 4032,
            height: 3024,
        },
        preview: {
            src: "/media/gallery/bulb/img-3133.preview.webp",
            width: 1600,
            height: 1200,
        },
        thumb: {
            src: "/media/gallery/bulb/img-3133.thumb.webp",
            width: 480,
            height: 360,
        },
    },
    "gallery/cliffside-quadruped-10": {
        full: {
            src: "/media/gallery/cliffside-quadruped-10.full.png",
            width: 600,
            height: 500,
        },
        preview: {
            src: "/media/gallery/cliffside-quadruped-10.preview.webp",
            width: 600,
            height: 500,
        },
        thumb: {
            src: "/media/gallery/cliffside-quadruped-10.thumb.webp",
            width: 480,
            height: 400,
        },
    },
    "gallery/colors": {
        full: {
            src: "/media/gallery/colors.full.png",
            width: 4094,
            height: 2355,
        },
        preview: {
            src: "/media/gallery/colors.preview.webp",
            width: 1600,
            height: 920,
        },
        thumb: {
            src: "/media/gallery/colors.thumb.webp",
            width: 480,
            height: 276,
        },
    },
    "gallery/cool": {
        full: {
            src: "/media/gallery/cool.full.png",
            width: 3176,
            height: 1824,
        },
        preview: {
            src: "/media/gallery/cool.preview.webp",
            width: 1600,
            height: 918,
        },
        thumb: {
            src: "/media/gallery/cool.thumb.webp",
            width: 480,
            height: 275,
        },
    },
    "gallery/cropped": {
        full: {
            src: "/media/gallery/cropped.full.jpg",
            width: 1936,
            height: 1832,
        },
        preview: {
            src: "/media/gallery/cropped.preview.webp",
            width: 1600,
            height: 1514,
        },
        thumb: {
            src: "/media/gallery/cropped.thumb.webp",
            width: 480,
            height: 454,
        },
    },
    "gallery/dancey": {
        full: {
            src: "/media/gallery/dancey.full.png",
            width: 1920,
            height: 1080,
        },
        preview: {
            src: "/media/gallery/dancey.preview.webp",
            width: 1600,
            height: 900,
        },
        thumb: {
            src: "/media/gallery/dancey.thumb.webp",
            width: 480,
            height: 270,
        },
    },
    "gallery/db": {
        full: {
            src: "/media/gallery/db.full.png",
            width: 1920,
            height: 1080,
        },
        preview: {
            src: "/media/gallery/db.preview.webp",
            width: 1600,
            height: 900,
        },
        thumb: {
            src: "/media/gallery/db.thumb.webp",
            width: 480,
            height: 270,
        },
    },
    "gallery/default-da-mock": {
        full: {
            src: "/media/gallery/default-da-mock.full.png",
            width: 100,
            height: 100,
        },
        preview: {
            src: "/media/gallery/default-da-mock.preview.webp",
            width: 100,
            height: 100,
        },
        thumb: {
            src: "/media/gallery/default-da-mock.thumb.webp",
            width: 100,
            height: 100,
        },
    },
    "gallery/discord-bio-easter-egg/bananaf": {
        full: {
            src: "/media/gallery/discord-bio-easter-egg/bananaf.full.png",
            width: 259,
            height: 219,
        },
        preview: {
            src: "/media/gallery/discord-bio-easter-egg/bananaf.preview.webp",
            width: 259,
            height: 219,
        },
        thumb: {
            src: "/media/gallery/discord-bio-easter-egg/bananaf.thumb.webp",
            width: 259,
            height: 219,
        },
    },
    "gallery/discord-bio-easter-egg/conkyf-alpha": {
        full: {
            src: "/media/gallery/discord-bio-easter-egg/conkyf-alpha.full.png",
            width: 1738,
            height: 1392,
        },
        preview: {
            src: "/media/gallery/discord-bio-easter-egg/conkyf-alpha.preview.webp",
            width: 1600,
            height: 1281,
        },
        thumb: {
            src: "/media/gallery/discord-bio-easter-egg/conkyf-alpha.thumb.webp",
            width: 480,
            height: 384,
        },
    },
    "gallery/discord-bio-easter-egg/drawmeadragon-p4rp": {
        full: {
            src: "/media/gallery/discord-bio-easter-egg/drawmeadragon-p4rp.full.png",
            width: 400,
            height: 300,
        },
        preview: {
            src: "/media/gallery/discord-bio-easter-egg/drawmeadragon-p4rp.preview.webp",
            width: 400,
            height: 300,
        },
        thumb: {
            src: "/media/gallery/discord-bio-easter-egg/drawmeadragon-p4rp.thumb.webp",
            width: 400,
            height: 300,
        },
    },
    "gallery/discord-bio-easter-egg/epif": {
        full: {
            src: "/media/gallery/discord-bio-easter-egg/epif.full.png",
            width: 937,
            height: 484,
        },
        preview: {
            src: "/media/gallery/discord-bio-easter-egg/epif.preview.webp",
            width: 937,
            height: 484,
        },
        thumb: {
            src: "/media/gallery/discord-bio-easter-egg/epif.thumb.webp",
            width: 480,
            height: 247,
        },
    },
    "gallery/discord-bio-easter-egg/gustf": {
        full: {
            src: "/media/gallery/discord-bio-easter-egg/gustf.full.png",
            width: 400,
            height: 300,
        },
        preview: {
            src: "/media/gallery/discord-bio-easter-egg/gustf.preview.webp",
            width: 400,
            height: 300,
        },
        thumb: {
            src: "/media/gallery/discord-bio-easter-egg/gustf.thumb.webp",
            width: 400,
            height: 300,
        },
    },
    "gallery/discord-bio-easter-egg/matsf": {
        full: {
            src: "/media/gallery/discord-bio-easter-egg/matsf.full.png",
            width: 256,
            height: 256,
        },
        preview: {
            src: "/media/gallery/discord-bio-easter-egg/matsf.preview.webp",
            width: 256,
            height: 256,
        },
        thumb: {
            src: "/media/gallery/discord-bio-easter-egg/matsf.thumb.webp",
            width: 256,
            height: 256,
        },
    },
    "gallery/discord-bio-easter-egg/poopyf-alpha": {
        full: {
            src: "/media/gallery/discord-bio-easter-egg/poopyf-alpha.full.png",
            width: 400,
            height: 300,
        },
        preview: {
            src: "/media/gallery/discord-bio-easter-egg/poopyf-alpha.preview.webp",
            width: 400,
            height: 300,
        },
        thumb: {
            src: "/media/gallery/discord-bio-easter-egg/poopyf-alpha.thumb.webp",
            width: 400,
            height: 300,
        },
    },
    "gallery/discord-bio-easter-egg/samclusterf": {
        full: {
            src: "/media/gallery/discord-bio-easter-egg/samclusterf.full.png",
            width: 400,
            height: 300,
        },
        preview: {
            src: "/media/gallery/discord-bio-easter-egg/samclusterf.preview.webp",
            width: 400,
            height: 300,
        },
        thumb: {
            src: "/media/gallery/discord-bio-easter-egg/samclusterf.thumb.webp",
            width: 400,
            height: 300,
        },
    },
    "gallery/discord-bio-easter-egg/sampcanef": {
        full: {
            src: "/media/gallery/discord-bio-easter-egg/sampcanef.full.png",
            width: 285,
            height: 257,
        },
        preview: {
            src: "/media/gallery/discord-bio-easter-egg/sampcanef.preview.webp",
            width: 285,
            height: 257,
        },
        thumb: {
            src: "/media/gallery/discord-bio-easter-egg/sampcanef.thumb.webp",
            width: 285,
            height: 257,
        },
    },
    "gallery/discord-bio-easter-egg/squaresquaref": {
        full: {
            src: "/media/gallery/discord-bio-easter-egg/squaresquaref.full.png",
            width: 860,
            height: 509,
        },
        preview: {
            src: "/media/gallery/discord-bio-easter-egg/squaresquaref.preview.webp",
            width: 860,
            height: 509,
        },
        thumb: {
            src: "/media/gallery/discord-bio-easter-egg/squaresquaref.thumb.webp",
            width: 480,
            height: 284,
        },
    },
    "gallery/discord-bio-easter-egg/tocky2f-alpha": {
        full: {
            src: "/media/gallery/discord-bio-easter-egg/tocky2f-alpha.full.png",
            width: 695,
            height: 478,
        },
        preview: {
            src: "/media/gallery/discord-bio-easter-egg/tocky2f-alpha.preview.webp",
            width: 695,
            height: 478,
        },
        thumb: {
            src: "/media/gallery/discord-bio-easter-egg/tocky2f-alpha.thumb.webp",
            width: 480,
            height: 330,
        },
    },
    "gallery/discord-bio-easter-egg/twf2ff": {
        full: {
            src: "/media/gallery/discord-bio-easter-egg/twf2ff.full.png",
            width: 649,
            height: 501,
        },
        preview: {
            src: "/media/gallery/discord-bio-easter-egg/twf2ff.preview.webp",
            width: 649,
            height: 501,
        },
        thumb: {
            src: "/media/gallery/discord-bio-easter-egg/twf2ff.thumb.webp",
            width: 480,
            height: 370,
        },
    },
    "gallery/discord-bio-easter-egg/vanv": {
        full: {
            src: "/media/gallery/discord-bio-easter-egg/vanv.full.png",
            width: 502,
            height: 614,
        },
        preview: {
            src: "/media/gallery/discord-bio-easter-egg/vanv.preview.webp",
            width: 502,
            height: 614,
        },
        thumb: {
            src: "/media/gallery/discord-bio-easter-egg/vanv.thumb.webp",
            width: 392,
            height: 480,
        },
    },
    "gallery/dragonraffle/automaton": {
        full: {
            src: "/media/gallery/dragonraffle/automaton.full.png",
            width: 4632,
            height: 2736,
        },
        preview: {
            src: "/media/gallery/dragonraffle/automaton.preview.webp",
            width: 1600,
            height: 945,
        },
        thumb: {
            src: "/media/gallery/dragonraffle/automaton.thumb.webp",
            width: 480,
            height: 283,
        },
    },
    "gallery/dragonraffle/dragon-in-rural-middle-america": {
        full: {
            src: "/media/gallery/dragonraffle/dragon-in-rural-middle-america.full.png",
            width: 3200,
            height: 1600,
        },
        preview: {
            src: "/media/gallery/dragonraffle/dragon-in-rural-middle-america.preview.webp",
            width: 1600,
            height: 800,
        },
        thumb: {
            src: "/media/gallery/dragonraffle/dragon-in-rural-middle-america.thumb.webp",
            width: 480,
            height: 240,
        },
    },
    "gallery/dragonraffle/dragon-on-lawn": {
        full: {
            src: "/media/gallery/dragonraffle/dragon-on-lawn.full.png",
            width: 1440,
            height: 1440,
        },
        preview: {
            src: "/media/gallery/dragonraffle/dragon-on-lawn.preview.webp",
            width: 1440,
            height: 1440,
        },
        thumb: {
            src: "/media/gallery/dragonraffle/dragon-on-lawn.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/dragonraffle/lexi": {
        full: {
            src: "/media/gallery/dragonraffle/lexi.full.png",
            width: 3252,
            height: 1896,
        },
        preview: {
            src: "/media/gallery/dragonraffle/lexi.preview.webp",
            width: 1600,
            height: 932,
        },
        thumb: {
            src: "/media/gallery/dragonraffle/lexi.thumb.webp",
            width: 480,
            height: 279,
        },
    },
    "gallery/dragonraffle/milli": {
        full: {
            src: "/media/gallery/dragonraffle/milli.full.png",
            width: 2410,
            height: 1134,
        },
        preview: {
            src: "/media/gallery/dragonraffle/milli.preview.webp",
            width: 1600,
            height: 752,
        },
        thumb: {
            src: "/media/gallery/dragonraffle/milli.thumb.webp",
            width: 480,
            height: 225,
        },
    },
    "gallery/dragonraffle/nuts": {
        full: {
            src: "/media/gallery/dragonraffle/nuts.full.png",
            width: 3840,
            height: 2160,
        },
        preview: {
            src: "/media/gallery/dragonraffle/nuts.preview.webp",
            width: 1600,
            height: 900,
        },
        thumb: {
            src: "/media/gallery/dragonraffle/nuts.thumb.webp",
            width: 480,
            height: 270,
        },
    },
    "gallery/dragonraffle/unnick-dragon-kiss": {
        full: {
            src: "/media/gallery/dragonraffle/unnick-dragon-kiss.full.png",
            width: 2160,
            height: 1220,
        },
        preview: {
            src: "/media/gallery/dragonraffle/unnick-dragon-kiss.preview.webp",
            width: 1600,
            height: 903,
        },
        thumb: {
            src: "/media/gallery/dragonraffle/unnick-dragon-kiss.thumb.webp",
            width: 480,
            height: 271,
        },
    },
    "gallery/drawception-1586753845-cropped": {
        full: {
            src: "/media/gallery/drawception-1586753845-cropped.full.png",
            width: 566,
            height: 435,
        },
        preview: {
            src: "/media/gallery/drawception-1586753845-cropped.preview.webp",
            width: 566,
            height: 435,
        },
        thumb: {
            src: "/media/gallery/drawception-1586753845-cropped.thumb.webp",
            width: 480,
            height: 368,
        },
    },
    "gallery/fdyf": {
        full: {
            src: "/media/gallery/fdyf.full.png",
            width: 933,
            height: 642,
        },
        preview: {
            src: "/media/gallery/fdyf.preview.webp",
            width: 933,
            height: 642,
        },
        thumb: {
            src: "/media/gallery/fdyf.thumb.webp",
            width: 480,
            height: 330,
        },
    },
    "gallery/fh": {
        full: {
            src: "/media/gallery/fh.full.png",
            width: 3840,
            height: 2160,
        },
        preview: {
            src: "/media/gallery/fh.preview.webp",
            width: 1600,
            height: 900,
        },
        thumb: {
            src: "/media/gallery/fh.thumb.webp",
            width: 480,
            height: 270,
        },
    },
    "gallery/goldenmak": {
        full: {
            src: "/media/gallery/goldenmak.full.png",
            width: 986,
            height: 1247,
        },
        preview: {
            src: "/media/gallery/goldenmak.preview.webp",
            width: 986,
            height: 1247,
        },
        thumb: {
            src: "/media/gallery/goldenmak.thumb.webp",
            width: 379,
            height: 480,
        },
    },
    "gallery/graffiti": {
        full: {
            src: "/media/gallery/graffiti.full.png",
            width: 2631,
            height: 1518,
        },
        preview: {
            src: "/media/gallery/graffiti.preview.webp",
            width: 1600,
            height: 923,
        },
        thumb: {
            src: "/media/gallery/graffiti.thumb.webp",
            width: 480,
            height: 276,
        },
    },
    "gallery/in-skylight": {
        full: {
            src: "/media/gallery/in-skylight.full.png",
            width: 1970,
            height: 1650,
        },
        preview: {
            src: "/media/gallery/in-skylight.preview.webp",
            width: 1600,
            height: 1340,
        },
        thumb: {
            src: "/media/gallery/in-skylight.thumb.webp",
            width: 480,
            height: 402,
        },
    },
    "gallery/iywralyx": {
        full: {
            src: "/media/gallery/iywralyx.full.png",
            width: 5000,
            height: 2132,
        },
        preview: {
            src: "/media/gallery/iywralyx.preview.webp",
            width: 1600,
            height: 682,
        },
        thumb: {
            src: "/media/gallery/iywralyx.thumb.webp",
            width: 480,
            height: 204,
        },
    },
    "gallery/janker": {
        full: {
            src: "/media/gallery/janker.full.png",
            width: 593,
            height: 438,
        },
        preview: {
            src: "/media/gallery/janker.preview.webp",
            width: 593,
            height: 438,
        },
        thumb: {
            src: "/media/gallery/janker.thumb.webp",
            width: 480,
            height: 354,
        },
    },
    "gallery/jankman-borzoi": {
        full: {
            src: "/media/gallery/jankman-borzoi.full.png",
            width: 1800,
            height: 1200,
        },
        preview: {
            src: "/media/gallery/jankman-borzoi.preview.webp",
            width: 1600,
            height: 1066,
        },
        thumb: {
            src: "/media/gallery/jankman-borzoi.thumb.webp",
            width: 480,
            height: 320,
        },
    },
    "gallery/just-gotta-ok-tired-of-ms-paint-now": {
        full: {
            src: "/media/gallery/just-gotta-ok-tired-of-ms-paint-now.full.png",
            width: 1125,
            height: 1068,
        },
        preview: {
            src: "/media/gallery/just-gotta-ok-tired-of-ms-paint-now.preview.webp",
            width: 1125,
            height: 1068,
        },
        thumb: {
            src: "/media/gallery/just-gotta-ok-tired-of-ms-paint-now.thumb.webp",
            width: 480,
            height: 455,
        },
    },
    "gallery/linky-drinkf": {
        full: {
            src: "/media/gallery/linky-drinkf.full.png",
            width: 1376,
            height: 852,
        },
        preview: {
            src: "/media/gallery/linky-drinkf.preview.webp",
            width: 1376,
            height: 852,
        },
        thumb: {
            src: "/media/gallery/linky-drinkf.thumb.webp",
            width: 480,
            height: 297,
        },
    },
    "gallery/mawdelyn-ref": {
        full: {
            src: "/media/gallery/mawdelyn-ref.full.png",
            width: 6280,
            height: 3400,
        },
        preview: {
            src: "/media/gallery/mawdelyn-ref.preview.webp",
            width: 1600,
            height: 866,
        },
        thumb: {
            src: "/media/gallery/mawdelyn-ref.thumb.webp",
            width: 480,
            height: 259,
        },
    },
    "gallery/nullcard": {
        full: {
            src: "/media/gallery/nullcard.full.png",
            width: 700,
            height: 700,
        },
        preview: {
            src: "/media/gallery/nullcard.preview.webp",
            width: 700,
            height: 700,
        },
        thumb: {
            src: "/media/gallery/nullcard.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/pixel-dino-fedora": {
        full: {
            src: "/media/gallery/pixel-dino-fedora.full.png",
            width: 50,
            height: 50,
        },
        preview: {
            src: "/media/gallery/pixel-dino-fedora.preview.webp",
            width: 50,
            height: 50,
        },
        thumb: {
            src: "/media/gallery/pixel-dino-fedora.thumb.webp",
            width: 50,
            height: 50,
        },
    },
    "gallery/pixel-dino-fedora-alt": {
        full: {
            src: "/media/gallery/pixel-dino-fedora-alt.full.png",
            width: 50,
            height: 50,
        },
        preview: {
            src: "/media/gallery/pixel-dino-fedora-alt.preview.webp",
            width: 50,
            height: 50,
        },
        thumb: {
            src: "/media/gallery/pixel-dino-fedora-alt.thumb.webp",
            width: 50,
            height: 50,
        },
    },
    "gallery/pixel-dino-fedora-cropped": {
        full: {
            src: "/media/gallery/pixel-dino-fedora-cropped.full.png",
            width: 50,
            height: 50,
        },
        preview: {
            src: "/media/gallery/pixel-dino-fedora-cropped.preview.webp",
            width: 50,
            height: 50,
        },
        thumb: {
            src: "/media/gallery/pixel-dino-fedora-cropped.thumb.webp",
            width: 50,
            height: 50,
        },
    },
    "gallery/pondy": {
        full: {
            src: "/media/gallery/pondy.full.png",
            width: 4220,
            height: 2160,
        },
        preview: {
            src: "/media/gallery/pondy.preview.webp",
            width: 1600,
            height: 818,
        },
        thumb: {
            src: "/media/gallery/pondy.thumb.webp",
            width: 480,
            height: 245,
        },
    },
    "gallery/pretbath": {
        full: {
            src: "/media/gallery/pretbath.full.png",
            width: 3702,
            height: 2022,
        },
        preview: {
            src: "/media/gallery/pretbath.preview.webp",
            width: 1600,
            height: 873,
        },
        thumb: {
            src: "/media/gallery/pretbath.thumb.webp",
            width: 480,
            height: 262,
        },
    },
    "gallery/quickdragon": {
        full: {
            src: "/media/gallery/quickdragon.full.png",
            width: 586,
            height: 342,
        },
        preview: {
            src: "/media/gallery/quickdragon.preview.webp",
            width: 586,
            height: 342,
        },
        thumb: {
            src: "/media/gallery/quickdragon.thumb.webp",
            width: 480,
            height: 280,
        },
    },
    "gallery/raiko3": {
        full: {
            src: "/media/gallery/raiko3.full.png",
            width: 724,
            height: 761,
        },
        preview: {
            src: "/media/gallery/raiko3.preview.webp",
            width: 724,
            height: 761,
        },
        thumb: {
            src: "/media/gallery/raiko3.thumb.webp",
            width: 456,
            height: 480,
        },
    },
    "gallery/recpo": {
        full: {
            src: "/media/gallery/recpo.full.png",
            width: 1920,
            height: 2960,
        },
        preview: {
            src: "/media/gallery/recpo.preview.webp",
            width: 1037,
            height: 1600,
        },
        thumb: {
            src: "/media/gallery/recpo.thumb.webp",
            width: 311,
            height: 480,
        },
    },
    "gallery/render-test": {
        full: {
            src: "/media/gallery/render-test.full.png",
            width: 1776,
            height: 1397,
        },
        preview: {
            src: "/media/gallery/render-test.preview.webp",
            width: 1600,
            height: 1258,
        },
        thumb: {
            src: "/media/gallery/render-test.thumb.webp",
            width: 480,
            height: 377,
        },
    },
    "gallery/scry": {
        full: {
            src: "/media/gallery/scry.full.png",
            width: 675,
            height: 398,
        },
        preview: {
            src: "/media/gallery/scry.preview.webp",
            width: 675,
            height: 398,
        },
        thumb: {
            src: "/media/gallery/scry.thumb.webp",
            width: 480,
            height: 283,
        },
    },
    "gallery/silver-vaie": {
        full: {
            src: "/media/gallery/silver-vaie.full.png",
            width: 3723,
            height: 2015,
        },
        preview: {
            src: "/media/gallery/silver-vaie.preview.webp",
            width: 1600,
            height: 865,
        },
        thumb: {
            src: "/media/gallery/silver-vaie.thumb.webp",
            width: 480,
            height: 259,
        },
    },
    "gallery/spax-dragon": {
        full: {
            src: "/media/gallery/spax-dragon.full.png",
            width: 2586,
            height: 1080,
        },
        preview: {
            src: "/media/gallery/spax-dragon.preview.webp",
            width: 1600,
            height: 668,
        },
        thumb: {
            src: "/media/gallery/spax-dragon.thumb.webp",
            width: 480,
            height: 200,
        },
    },
    "gallery/swimmy": {
        full: {
            src: "/media/gallery/swimmy.full.png",
            width: 3000,
            height: 1800,
        },
        preview: {
            src: "/media/gallery/swimmy.preview.webp",
            width: 1600,
            height: 960,
        },
        thumb: {
            src: "/media/gallery/swimmy.thumb.webp",
            width: 480,
            height: 288,
        },
    },
    "gallery/terskayl-2": {
        full: {
            src: "/media/gallery/terskayl-2.full.png",
            width: 3518,
            height: 2251,
        },
        preview: {
            src: "/media/gallery/terskayl-2.preview.webp",
            width: 1600,
            height: 1023,
        },
        thumb: {
            src: "/media/gallery/terskayl-2.thumb.webp",
            width: 480,
            height: 307,
        },
    },
    "gallery/terskayl-train-station-signed-vaiezzell": {
        full: {
            src: "/media/gallery/terskayl-train-station-signed-vaiezzell.full.png",
            width: 2297,
            height: 1580,
        },
        preview: {
            src: "/media/gallery/terskayl-train-station-signed-vaiezzell.preview.webp",
            width: 1600,
            height: 1100,
        },
        thumb: {
            src: "/media/gallery/terskayl-train-station-signed-vaiezzell.thumb.webp",
            width: 480,
            height: 330,
        },
    },
    "gallery/tetherball2": {
        full: {
            src: "/media/gallery/tetherball2.full.png",
            width: 2500,
            height: 1500,
        },
        preview: {
            src: "/media/gallery/tetherball2.preview.webp",
            width: 1600,
            height: 960,
        },
        thumb: {
            src: "/media/gallery/tetherball2.thumb.webp",
            width: 480,
            height: 288,
        },
    },
    "gallery/the-good-legs": {
        full: {
            src: "/media/gallery/the-good-legs.full.jpg",
            width: 6085,
            height: 4890,
        },
        preview: {
            src: "/media/gallery/the-good-legs.preview.webp",
            width: 1600,
            height: 1285,
        },
        thumb: {
            src: "/media/gallery/the-good-legs.thumb.webp",
            width: 480,
            height: 385,
        },
    },
    "gallery/treey": {
        full: {
            src: "/media/gallery/treey.full.png",
            width: 688,
            height: 357,
        },
        preview: {
            src: "/media/gallery/treey.preview.webp",
            width: 688,
            height: 357,
        },
        thumb: {
            src: "/media/gallery/treey.thumb.webp",
            width: 480,
            height: 249,
        },
    },
    "gallery/unknown": {
        full: {
            src: "/media/gallery/unknown.full.png",
            width: 942,
            height: 668,
        },
        preview: {
            src: "/media/gallery/unknown.preview.webp",
            width: 942,
            height: 668,
        },
        thumb: {
            src: "/media/gallery/unknown.thumb.webp",
            width: 480,
            height: 340,
        },
    },
    "gallery/userbox-meester": {
        full: {
            src: "/media/gallery/userbox-meester.full.png",
            width: 600,
            height: 600,
        },
        preview: {
            src: "/media/gallery/userbox-meester.preview.webp",
            width: 600,
            height: 600,
        },
        thumb: {
            src: "/media/gallery/userbox-meester.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/userbox-midnight": {
        full: {
            src: "/media/gallery/userbox-midnight.full.png",
            width: 600,
            height: 600,
        },
        preview: {
            src: "/media/gallery/userbox-midnight.preview.webp",
            width: 600,
            height: 600,
        },
        thumb: {
            src: "/media/gallery/userbox-midnight.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/userbox-yessoan": {
        full: {
            src: "/media/gallery/userbox-yessoan.full.png",
            width: 600,
            height: 600,
        },
        preview: {
            src: "/media/gallery/userbox-yessoan.preview.webp",
            width: 600,
            height: 600,
        },
        thumb: {
            src: "/media/gallery/userbox-yessoan.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/vaie-dragn-emoji/dragnbrattynew": {
        full: {
            src: "/media/gallery/vaie-dragn-emoji/dragnbrattynew.full.png",
            width: 1024,
            height: 1024,
        },
        preview: {
            src: "/media/gallery/vaie-dragn-emoji/dragnbrattynew.preview.webp",
            width: 1024,
            height: 1024,
        },
        thumb: {
            src: "/media/gallery/vaie-dragn-emoji/dragnbrattynew.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/vaie-dragn-emoji/dragnmeltingweak": {
        full: {
            src: "/media/gallery/vaie-dragn-emoji/dragnmeltingweak.full.png",
            width: 1024,
            height: 1024,
        },
        preview: {
            src: "/media/gallery/vaie-dragn-emoji/dragnmeltingweak.preview.webp",
            width: 1024,
            height: 1024,
        },
        thumb: {
            src: "/media/gallery/vaie-dragn-emoji/dragnmeltingweak.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/vaie-dragn-emoji/dragnskull": {
        full: {
            src: "/media/gallery/vaie-dragn-emoji/dragnskull.full.png",
            width: 1080,
            height: 1080,
        },
        preview: {
            src: "/media/gallery/vaie-dragn-emoji/dragnskull.preview.webp",
            width: 1080,
            height: 1080,
        },
        thumb: {
            src: "/media/gallery/vaie-dragn-emoji/dragnskull.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/vaie-dragn-emoji/dragnwinghug": {
        full: {
            src: "/media/gallery/vaie-dragn-emoji/dragnwinghug.full.png",
            width: 1080,
            height: 1080,
        },
        preview: {
            src: "/media/gallery/vaie-dragn-emoji/dragnwinghug.preview.webp",
            width: 1080,
            height: 1080,
        },
        thumb: {
            src: "/media/gallery/vaie-dragn-emoji/dragnwinghug.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/vaie-dragn-emoji/zanayell": {
        full: {
            src: "/media/gallery/vaie-dragn-emoji/zanayell.full.png",
            width: 512,
            height: 512,
        },
        preview: {
            src: "/media/gallery/vaie-dragn-emoji/zanayell.preview.webp",
            width: 512,
            height: 512,
        },
        thumb: {
            src: "/media/gallery/vaie-dragn-emoji/zanayell.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/vaiezzell-circle": {
        full: {
            src: "/media/gallery/vaiezzell-circle.full.png",
            width: 1024,
            height: 1024,
        },
        preview: {
            src: "/media/gallery/vaiezzell-circle.preview.webp",
            width: 1024,
            height: 1024,
        },
        thumb: {
            src: "/media/gallery/vaiezzell-circle.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/vaiezzell-pfp-2025": {
        full: {
            src: "/media/gallery/vaiezzell-pfp-2025.full.png",
            width: 1440,
            height: 1440,
        },
        preview: {
            src: "/media/gallery/vaiezzell-pfp-2025.preview.webp",
            width: 1440,
            height: 1440,
        },
        thumb: {
            src: "/media/gallery/vaiezzell-pfp-2025.thumb.webp",
            width: 480,
            height: 480,
        },
    },
    "gallery/vaiezzell-ref": {
        full: {
            src: "/media/gallery/vaiezzell-ref.full.png",
            width: 6308,
            height: 3992,
        },
        preview: {
            src: "/media/gallery/vaiezzell-ref.preview.webp",
            width: 1600,
            height: 1012,
        },
        thumb: {
            src: "/media/gallery/vaiezzell-ref.thumb.webp",
            width: 480,
            height: 303,
        },
    },
    "gallery/walky-walky": {
        full: {
            src: "/media/gallery/walky-walky.full.png",
            width: 2000,
            height: 1279,
        },
        preview: {
            src: "/media/gallery/walky-walky.preview.webp",
            width: 1600,
            height: 1023,
        },
        thumb: {
            src: "/media/gallery/walky-walky.thumb.webp",
            width: 480,
            height: 306,
        },
    },
    "gallery/whiteboardy-derg": {
        full: {
            src: "/media/gallery/whiteboardy-derg.full.jpg",
            width: 4032,
            height: 1758,
        },
        preview: {
            src: "/media/gallery/whiteboardy-derg.preview.webp",
            width: 1600,
            height: 697,
        },
        thumb: {
            src: "/media/gallery/whiteboardy-derg.thumb.webp",
            width: 480,
            height: 209,
        },
    },
    "gallery/who-the-hell-is-jankman": {
        full: {
            src: "/media/gallery/who-the-hell-is-jankman.full.png",
            width: 1920,
            height: 1080,
        },
        preview: {
            src: "/media/gallery/who-the-hell-is-jankman.preview.webp",
            width: 1600,
            height: 900,
        },
        thumb: {
            src: "/media/gallery/who-the-hell-is-jankman.thumb.webp",
            width: 480,
            height: 270,
        },
    },
    "gallery/wires-airport": {
        full: {
            src: "/media/gallery/wires-airport.full.png",
            width: 2925,
            height: 1650,
        },
        preview: {
            src: "/media/gallery/wires-airport.preview.webp",
            width: 1600,
            height: 902,
        },
        thumb: {
            src: "/media/gallery/wires-airport.thumb.webp",
            width: 480,
            height: 270,
        },
    },
    "gallery/yay-dragon": {
        full: {
            src: "/media/gallery/yay-dragon.full.png",
            width: 1985,
            height: 1427,
        },
        preview: {
            src: "/media/gallery/yay-dragon.preview.webp",
            width: 1600,
            height: 1150,
        },
        thumb: {
            src: "/media/gallery/yay-dragon.thumb.webp",
            width: 480,
            height: 345,
        },
    },
    "gallery/yetanothersideview": {
        full: {
            src: "/media/gallery/yetanothersideview.full.png",
            width: 1081,
            height: 685,
        },
        preview: {
            src: "/media/gallery/yetanothersideview.preview.webp",
            width: 1081,
            height: 685,
        },
        thumb: {
            src: "/media/gallery/yetanothersideview.thumb.webp",
            width: 480,
            height: 304,
        },
    },
    "gallery/zanawyrm": {
        full: {
            src: "/media/gallery/zanawyrm.full.png",
            width: 1265,
            height: 1223,
        },
        preview: {
            src: "/media/gallery/zanawyrm.preview.webp",
            width: 1265,
            height: 1223,
        },
        thumb: {
            src: "/media/gallery/zanawyrm.thumb.webp",
            width: 480,
            height: 464,
        },
    },
    "gallery/zaneb": {
        full: {
            src: "/media/gallery/zaneb.full.png",
            width: 1546,
            height: 1200,
        },
        preview: {
            src: "/media/gallery/zaneb.preview.webp",
            width: 1546,
            height: 1200,
        },
        thumb: {
            src: "/media/gallery/zaneb.thumb.webp",
            width: 480,
            height: 372,
        },
    },
} satisfies Record<string, WorkEntryImageVariants>;
