use crate::convert_media::asset::{GeneratedGalleryImageAsset, read_generated_gallery_image_asset};
use crate::convert_media::config::Options;
use crate::convert_media::output_paths::metadata_key_of;
use crate::convert_media::pipeline::{GalleryConversionResult, StaticConversionResult};
use anyhow::Result;
use std::fs;

#[derive(Clone, Debug)]
struct GeneratedGalleryImage {
    full: GeneratedGalleryImageAsset,
    preview: GeneratedGalleryImageAsset,
    thumb: GeneratedGalleryImageAsset,
}

#[derive(Clone, Debug)]
struct GeneratedGalleryImageEntry {
    key: String,
    image: GeneratedGalleryImage,
}

#[derive(Clone, Debug)]
struct GeneratedMediaAssetEntry {
    key: String,
    asset: GeneratedGalleryImageAsset,
}

pub fn write_generated_gallery_images(
    conversion_results: &[GalleryConversionResult],
    options: &Options,
) -> Result<()> {
    let mut entries = conversion_results
        .iter()
        .map(|result| read_generated_gallery_image(result, options))
        .collect::<Result<Vec<_>>>()?;

    entries.sort_by(|a, b| a.key.cmp(&b.key));

    let mut lines = vec![
        "import type { GeneratedGalleryImage } from \"./GalleryImage\";".to_string(),
        String::new(),
        "// Generated by local-utils convert-media. Do not edit by hand.".to_string(),
        "export const generatedGalleryImages = {".to_string(),
    ];

    for entry in entries {
        push_entry_lines(&mut lines, &entry)?;
    }

    lines.push("} satisfies Record<string, GeneratedGalleryImage>;".to_string());
    lines.push(String::new());

    if let Some(parent) = options.metadata_output.parent() {
        fs::create_dir_all(parent)?;
    }

    fs::write(&options.metadata_output, lines.join("\n"))?;

    Ok(())
}

pub fn write_generated_media_assets(
    conversion_results: &[StaticConversionResult],
    options: &Options,
) -> Result<()> {
    let mut entries = conversion_results
        .iter()
        .map(|result| read_generated_media_asset(result, options))
        .collect::<Result<Vec<_>>>()?;

    entries.sort_by(|a, b| a.key.cmp(&b.key));

    let mut lines = vec![
        "import type { GalleryImageAsset } from \"./GalleryImage\";".to_string(),
        String::new(),
        "// Generated by local-utils convert-media. Do not edit by hand.".to_string(),
        "export const generatedMediaAssets = {".to_string(),
    ];

    for entry in entries {
        push_media_asset_entry_lines(&mut lines, &entry)?;
    }

    lines.push("} satisfies Record<string, GalleryImageAsset>;".to_string());
    lines.push(String::new());

    if let Some(parent) = options.media_assets_output.parent() {
        fs::create_dir_all(parent)?;
    }

    fs::write(&options.media_assets_output, lines.join("\n"))?;

    Ok(())
}

fn read_generated_gallery_image(
    conversion_result: &GalleryConversionResult,
    options: &Options,
) -> Result<GeneratedGalleryImageEntry> {
    Ok(GeneratedGalleryImageEntry {
        key: metadata_key_of(&conversion_result.file, options)?,
        image: GeneratedGalleryImage {
            full: read_generated_gallery_image_asset(
                &conversion_result.output_paths.full,
                options,
            )?,
            preview: read_generated_gallery_image_asset(
                &conversion_result.output_paths.preview,
                options,
            )?,
            thumb: read_generated_gallery_image_asset(
                &conversion_result.output_paths.thumb,
                options,
            )?,
        },
    })
}

fn read_generated_media_asset(
    conversion_result: &StaticConversionResult,
    options: &Options,
) -> Result<GeneratedMediaAssetEntry> {
    Ok(GeneratedMediaAssetEntry {
        key: metadata_key_of(&conversion_result.file, options)?,
        asset: read_generated_gallery_image_asset(&conversion_result.output_paths.webp, options)?,
    })
}

fn push_entry_lines(lines: &mut Vec<String>, entry: &GeneratedGalleryImageEntry) -> Result<()> {
    lines.push(format!("    {}: {{", serde_json::to_string(&entry.key)?));
    push_asset_lines(lines, "full", &entry.image.full)?;
    push_asset_lines(lines, "preview", &entry.image.preview)?;
    push_asset_lines(lines, "thumb", &entry.image.thumb)?;
    lines.push("    },".to_string());

    Ok(())
}

fn push_media_asset_entry_lines(
    lines: &mut Vec<String>,
    entry: &GeneratedMediaAssetEntry,
) -> Result<()> {
    lines.push(format!("    {}: {{", serde_json::to_string(&entry.key)?));
    push_asset_field_lines(lines, &entry.asset, "        ")?;
    lines.push("    },".to_string());

    Ok(())
}

fn push_asset_lines(
    lines: &mut Vec<String>,
    label: &str,
    asset: &GeneratedGalleryImageAsset,
) -> Result<()> {
    lines.push(format!("        {label}: {{"));
    push_asset_field_lines(lines, asset, "            ")?;
    lines.push("        },".to_string());

    Ok(())
}

fn push_asset_field_lines(
    lines: &mut Vec<String>,
    asset: &GeneratedGalleryImageAsset,
    indent: &str,
) -> Result<()> {
    lines.push(format!(
        "{indent}src: {},",
        serde_json::to_string(&asset.src)?
    ));
    lines.push(format!("{indent}width: {},", asset.width));
    lines.push(format!("{indent}height: {},", asset.height));

    Ok(())
}
